apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - config-map.yaml
  - gateway-deployment.yaml
  - gateway-services.yaml
  - gateway-pdb.yaml
  - network-policy.yaml
commonLabels:
  app.kubernetes.io/name: ax-serving
  app.kubernetes.io/part-of: ax-serving
