[package]
name = "ax-serving-protocol"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
