//! ax-serving-shim: llama.h C API drop-in compatibility shim.
//!
//! Produces `libllama.dylib`. All public functions are `#[no_mangle] extern "C"`
//! matching llama.h signatures. Header generated by `cbindgen`; never hand-edited.
//!
//! # Safety Contract
//!
//! - Every extern "C" function checks for null pointers before dereferencing.
//! - `Box::into_raw` / `Box::from_raw` are the ONLY raw pointer operations.
//! - No raw pointer is stored across function call boundaries.
//! - `LlamaModel` is Send + Sync; `LlamaContext` is single-threaded (matches llama.cpp).
//!
//! # Design
//!
//! All unsafe pointer operations are confined to this crate. No other ax-serving
//! crate uses unsafe code (except platform-specific FFI in ax-serving-engine).

#![allow(clippy::not_unsafe_ptr_arg_deref)]

#[cfg(not(all(target_arch = "aarch64", target_os = "macos")))]
compile_error!("ax-serving-shim only supports aarch64-apple-darwin (Apple Silicon M3+)");

pub mod context;
pub mod model;
pub mod sampling;
pub mod tokenize;
pub mod types;

pub use types::{LlamaContext, LlamaModel};

// ── Backend init / free ───────────────────────────────────────────────────────

/// Initialize the inference backend. Must be called before any other function.
///
/// `numa` is ignored (Apple Silicon has no NUMA topology).
#[unsafe(no_mangle)]
pub extern "C" fn llama_backend_init(_numa: bool) {
    // Initialize tracing subscriber for the shim.
    // Safe to call multiple times (subscriber is a OnceLock).
    let _ = tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_env("AXS_LOG")
                .add_directive(tracing::Level::WARN.into()),
        )
        .try_init();
}

/// Free backend resources. No-op in ax-serving (resources freed on drop).
#[unsafe(no_mangle)]
pub extern "C" fn llama_backend_free() {}

/// Return current wall-clock time in microseconds since UNIX epoch.
///
/// Matches llama.cpp's `llama_time_us()` — useful for benchmarking and
/// computing elapsed time between calls.
#[unsafe(no_mangle)]
pub extern "C" fn llama_time_us() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_micros() as i64)
        .unwrap_or(0)
}

/// Return a null-terminated string describing the inference backend.
///
/// The returned pointer is static — never free it.
#[unsafe(no_mangle)]
pub extern "C" fn llama_system_info() -> *const libc::c_char {
    static INFO: &std::ffi::CStr = c"ax-serving (mistralrs-core + Candle Metal / Apple Silicon)";
    INFO.as_ptr()
}
