use std::collections::BTreeMap;
use std::io::Write;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};

/// Default listen/advertised address for the Thor agent proxy.
const DEFAULT_THOR_LISTEN_ADDR: &str = "0.0.0.0:18081";
/// Default SGLang (or vLLM) runtime URL on the same host.
const DEFAULT_SGLANG_URL: &str = "http://127.0.0.1:30000";

const THOR_ENV_KEYS: &[&str] = &[
    "AXS_CONTROL_PLANE_URL",
    "AXS_WORKER_TOKEN",
    "AXS_SGLANG_URL",
    "AXS_THOR_BACKEND",
    "AXS_THOR_RUNTIME_URL",
    "AXS_THOR_LISTEN_ADDR",
    "AXS_THOR_ADVERTISED_ADDR",
    "AXS_THOR_MAX_INFLIGHT",
    "AXS_THOR_MAX_CONTEXT",
    "AXS_THOR_WORKER_POOL",
    "AXS_THOR_NODE_CLASS",
    "AXS_THOR_FRIENDLY_NAME",
    "AXS_THOR_CHIP_MODEL",
    "AXS_THOR_WORKER_ID_PATH",
];

const THOR_NOT_READY_EXIT_CODE: i32 = 24;

pub struct InstallArgs {
    pub control_plane: Option<String>,
    pub listen_addr: String,
    pub advertised_addr: Option<String>,
    pub sglang_url: String,
    pub worker_token: Option<String>,
    pub max_inflight: usize,
    pub worker_pool: Option<String>,
    pub node_class: String,
    pub friendly_name: Option<String>,
    pub chip_model: Option<String>,
    pub output: Option<PathBuf>,
}

pub struct JoinArgs {
    pub control_plane: String,
    pub advertised_addr: Option<String>,
    pub listen_addr: Option<String>,
    pub sglang_url: Option<String>,
    pub worker_token: Option<String>,
    pub max_inflight: Option<usize>,
    pub worker_pool: Option<String>,
    pub node_class: Option<String>,
    pub friendly_name: Option<String>,
    pub chip_model: Option<String>,
    pub output: Option<PathBuf>,
}

pub struct StatusArgs {
    pub config: Option<PathBuf>,
    pub require_ready: bool,
}

pub struct WaitReadyArgs {
    pub config: Option<PathBuf>,
    pub timeout_secs: u64,
    pub poll_interval_ms: u64,
}

pub struct DrainArgs {
    pub config: Option<PathBuf>,
    pub complete_when_idle: bool,
    pub idle_timeout_secs: u64,
}

#[derive(Clone, Debug, Default)]
struct ThorEnvFile {
    values: BTreeMap<String, String>,
}

impl ThorEnvFile {
    fn read(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        let mut values = BTreeMap::new();
        for raw_line in content.lines() {
            let line = raw_line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                continue;
            };
            values.insert(key.trim().to_string(), value.trim().to_string());
        }
        Ok(Self { values })
    }

    fn write(&self, path: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("failed to create {}", parent.display()))?;
        }

        let mut file = std::fs::File::create(path)
            .with_context(|| format!("failed to write {}", path.display()))?;
        writeln!(file, "# ax-thor-agent environment file")?;
        writeln!(file, "# generated by `ax-serving thor`")?;
        for key in THOR_ENV_KEYS {
            if let Some(value) = self.values.get(*key) {
                writeln!(file, "{key}={value}")?;
            }
        }
        Ok(())
    }

    fn set(&mut self, key: &str, value: Option<String>) {
        match value {
            Some(value) if !value.trim().is_empty() => {
                self.values
                    .insert(key.to_string(), value.trim().to_string());
            }
            _ => {
                self.values.remove(key);
            }
        }
    }

    fn get(&self, key: &str) -> Option<&str> {
        self.values.get(key).map(String::as_str)
    }

    fn set_if_some(&mut self, key: &str, value: Option<String>) {
        if let Some(value) = value {
            self.set(key, Some(value));
        }
    }
}

pub fn install(args: InstallArgs) -> Result<()> {
    let path = args.output.unwrap_or_else(default_thor_env_path);
    let listen_addr = parse_socket_addr(&args.listen_addr, "listen address")?;
    let advertised_addr = parse_socket_addr(
        args.advertised_addr.as_deref().unwrap_or(&args.listen_addr),
        "advertised address",
    )?;

    let mut env_file = if path.exists() {
        ThorEnvFile::read(&path)?
    } else {
        ThorEnvFile::default()
    };

    env_file.set(
        "AXS_CONTROL_PLANE_URL",
        args.control_plane.map(trim_trailing_slash),
    );
    env_file.set("AXS_THOR_BACKEND", Some("sglang".into()));
    env_file.set("AXS_SGLANG_URL", Some(trim_trailing_slash(args.sglang_url)));
    env_file.set(
        "AXS_THOR_RUNTIME_URL",
        env_file.get("AXS_SGLANG_URL").map(str::to_string),
    );
    env_file.set("AXS_WORKER_TOKEN", args.worker_token);
    env_file.set("AXS_THOR_LISTEN_ADDR", Some(listen_addr.to_string()));
    env_file.set(
        "AXS_THOR_ADVERTISED_ADDR",
        Some(advertised_addr.to_string()),
    );
    env_file.set(
        "AXS_THOR_MAX_INFLIGHT",
        Some(args.max_inflight.max(1).to_string()),
    );
    env_file.set("AXS_THOR_WORKER_POOL", args.worker_pool);
    env_file.set("AXS_THOR_NODE_CLASS", Some(args.node_class));
    env_file.set("AXS_THOR_FRIENDLY_NAME", args.friendly_name);
    env_file.set("AXS_THOR_CHIP_MODEL", args.chip_model);
    env_file.write(&path)?;

    print_preflight(&path, &env_file);
    Ok(())
}

pub async fn join(args: JoinArgs) -> Result<()> {
    let path = args.output.unwrap_or_else(default_thor_env_path);
    let mut env_file = if path.exists() {
        ThorEnvFile::read(&path)?
    } else {
        ThorEnvFile::default()
    };

    env_file.set(
        "AXS_CONTROL_PLANE_URL",
        Some(trim_trailing_slash(args.control_plane)),
    );
    env_file.set("AXS_THOR_BACKEND", Some("sglang".into()));
    env_file.set_if_some("AXS_WORKER_TOKEN", args.worker_token);
    env_file.set_if_some("AXS_SGLANG_URL", args.sglang_url.map(trim_trailing_slash));
    if let Some(runtime_url) = env_file.get("AXS_SGLANG_URL") {
        env_file.set("AXS_THOR_RUNTIME_URL", Some(runtime_url.to_string()));
    }
    if let Some(listen_addr) = args.listen_addr {
        let listen_addr = parse_socket_addr(&listen_addr, "listen address")?;
        env_file.set("AXS_THOR_LISTEN_ADDR", Some(listen_addr.to_string()));
    }
    if let Some(advertised_addr) = args.advertised_addr {
        let advertised_addr = parse_socket_addr(&advertised_addr, "advertised address")?;
        env_file.set(
            "AXS_THOR_ADVERTISED_ADDR",
            Some(advertised_addr.to_string()),
        );
    }
    if let Some(max_inflight) = args.max_inflight {
        env_file.set(
            "AXS_THOR_MAX_INFLIGHT",
            Some(max_inflight.max(1).to_string()),
        );
    }
    env_file.set_if_some("AXS_THOR_WORKER_POOL", args.worker_pool);
    env_file.set_if_some("AXS_THOR_NODE_CLASS", args.node_class);
    env_file.set_if_some("AXS_THOR_FRIENDLY_NAME", args.friendly_name);
    env_file.set_if_some("AXS_THOR_CHIP_MODEL", args.chip_model);

    let control_plane = env_file
        .get("AXS_CONTROL_PLANE_URL")
        .context("AXS_CONTROL_PLANE_URL is required")?;
    let worker_token = env_file.get("AXS_WORKER_TOKEN").map(str::to_string);
    let listen_addr = env_file
        .get("AXS_THOR_LISTEN_ADDR")
        .unwrap_or(DEFAULT_THOR_LISTEN_ADDR);
    parse_socket_addr(listen_addr, "listen address")?;
    let advertised_addr = env_file
        .get("AXS_THOR_ADVERTISED_ADDR")
        .unwrap_or(listen_addr);
    parse_socket_addr(advertised_addr, "advertised address")?;

    let client = reqwest::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(3))
        .timeout(std::time::Duration::from_secs(5))
        .build()
        .context("failed to build HTTP client for join check")?;
    let check = control_plane_readiness(&client, control_plane, worker_token.as_deref()).await?;

    env_file.write(&path)?;
    println!("thor config updated: {}", path.display());
    println!("control plane: {}", control_plane);
    println!("readiness: {}", check.summary());
    println!("next: run `ax-thor-agent` with env from {}", path.display());
    Ok(())
}

pub async fn status(args: StatusArgs) -> Result<()> {
    let path = args.config.unwrap_or_else(default_thor_env_path);
    let report = collect_status_report(
        &path,
        std::time::Duration::from_secs(3),
        std::time::Duration::from_secs(5),
    )
    .await?;
    print_status_report(&report);
    if args.require_ready && !report.ready {
        eprintln!("thor status overall_state={}", report.overall_state);
        std::process::exit(THOR_NOT_READY_EXIT_CODE);
    }
    Ok(())
}

pub async fn wait_ready(args: WaitReadyArgs) -> Result<()> {
    let path = args.config.unwrap_or_else(default_thor_env_path);
    let timeout_secs = args.timeout_secs.max(1);
    let poll_interval_ms = args.poll_interval_ms.max(1);
    let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(timeout_secs);
    let connect_timeout = std::time::Duration::from_millis(200);
    let request_timeout = std::time::Duration::from_millis(500);
    let env_file = ThorEnvFile::read(&path)?;
    if resolve_worker_id(&env_file).is_none() {
        let report = fallback_status_report_from_env(path.clone(), &env_file)?;
        print_status_report(&report);
        eprintln!("thor wait-ready timed out after {timeout_secs}s");
        std::process::exit(THOR_NOT_READY_EXIT_CODE);
    }

    loop {
        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        let report = match tokio::time::timeout(
            remaining,
            collect_status_report(&path, connect_timeout, request_timeout),
        )
        .await
        {
            Ok(result) => result?,
            Err(_) => {
                let report = fallback_status_report(&path)?;
                print_status_report(&report);
                eprintln!("thor wait-ready timed out after {timeout_secs}s");
                std::process::exit(THOR_NOT_READY_EXIT_CODE);
            }
        };
        if report.ready {
            print_status_report(&report);
            return Ok(());
        }

        let now = tokio::time::Instant::now();
        if now >= deadline {
            print_status_report(&report);
            eprintln!("thor wait-ready timed out after {timeout_secs}s");
            std::process::exit(THOR_NOT_READY_EXIT_CODE);
        }

        let remaining = deadline.saturating_duration_since(now);
        tokio::time::sleep(remaining.min(std::time::Duration::from_millis(poll_interval_ms))).await;
        if tokio::time::Instant::now() >= deadline {
            print_status_report(&report);
            eprintln!("thor wait-ready timed out after {timeout_secs}s");
            std::process::exit(THOR_NOT_READY_EXIT_CODE);
        }
    }
}

pub fn wait_ready_fast_path(config: Option<PathBuf>, timeout_secs: u64) -> Result<()> {
    let path = config.unwrap_or_else(default_thor_env_path);
    let env_file = ThorEnvFile::read(&path)?;
    if resolve_worker_id(&env_file).is_none() {
        let report = fallback_status_report_from_env(path, &env_file)?;
        print_status_report(&report);
        eprintln!("thor wait-ready timed out after {}s", timeout_secs.max(1));
        std::process::exit(THOR_NOT_READY_EXIT_CODE);
    }
    Ok(())
}

pub async fn drain(args: DrainArgs) -> Result<()> {
    let path = args.config.unwrap_or_else(default_thor_env_path);
    let env_file = ThorEnvFile::read(&path)?;
    let control_plane = env_file
        .get("AXS_CONTROL_PLANE_URL")
        .context("AXS_CONTROL_PLANE_URL missing from thor config")?;
    let worker_id = resolve_worker_id(&env_file).context("thor worker_id is not available")?;
    let runtime_url = runtime_base_url(&env_file);
    let client = reqwest::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(3))
        .timeout(std::time::Duration::from_secs(5))
        .build()
        .context("failed to build HTTP client for thor drain")?;

    post_control_plane_action(
        &client,
        control_plane,
        env_file.get("AXS_WORKER_TOKEN"),
        &worker_id,
        "drain",
    )
    .await?;
    println!("thor drain requested for worker_id={worker_id}");

    if !args.complete_when_idle {
        return Ok(());
    }

    let deadline =
        tokio::time::Instant::now() + std::time::Duration::from_secs(args.idle_timeout_secs.max(1));
    loop {
        let health = probe_agent_health(&client, &format!("{runtime_url}/health")).await;
        if health.is_idle() {
            post_control_plane_action(
                &client,
                control_plane,
                env_file.get("AXS_WORKER_TOKEN"),
                &worker_id,
                "drain-complete",
            )
            .await?;
            println!("thor drain-complete sent for worker_id={worker_id}");
            return Ok(());
        }

        if tokio::time::Instant::now() >= deadline {
            anyhow::bail!(
                "thor agent did not become idle within {}s",
                args.idle_timeout_secs.max(1)
            );
        }

        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    }
}

fn default_thor_env_path() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config/ax-serving/thor.env")
}

fn trim_trailing_slash(input: String) -> String {
    input.trim().trim_end_matches('/').to_string()
}

fn parse_socket_addr(raw: &str, label: &str) -> Result<SocketAddr> {
    raw.parse()
        .with_context(|| format!("invalid {label}: '{raw}'"))
}

fn local_probe_base(listen_addr: SocketAddr) -> String {
    let ip = match listen_addr.ip() {
        IpAddr::V4(ip) if ip.is_unspecified() => IpAddr::V4(Ipv4Addr::LOCALHOST),
        IpAddr::V6(ip) if ip.is_unspecified() => IpAddr::V6(std::net::Ipv6Addr::LOCALHOST),
        ip => ip,
    };
    format!("http://{}:{}", ip, listen_addr.port())
}

fn print_preflight(path: &Path, env_file: &ThorEnvFile) {
    println!("thor config written: {}", path.display());
    println!(
        "control plane: {}",
        env_file.get("AXS_CONTROL_PLANE_URL").unwrap_or("<unset>")
    );
    println!(
        "listen addr: {}",
        env_file
            .get("AXS_THOR_LISTEN_ADDR")
            .unwrap_or(DEFAULT_THOR_LISTEN_ADDR)
    );
    println!(
        "advertised addr: {}",
        env_file
            .get("AXS_THOR_ADVERTISED_ADDR")
            .unwrap_or(DEFAULT_THOR_LISTEN_ADDR)
    );

    let docker = check_command("docker", &["--version"]);
    let cargo = check_command("cargo", &["--version"]);
    println!("docker: {}", docker);
    println!("cargo: {}", cargo);
    println!(
        "next: run `ax-serving thor join --control-plane <url>` and then launch `ax-thor-agent` with env from {}",
        path.display()
    );
}

fn check_command(program: &str, args: &[&str]) -> &'static str {
    match Command::new(program).args(args).output() {
        Ok(output) if output.status.success() => "ok",
        Ok(_) => "present but failing",
        Err(_) => "missing",
    }
}

struct ReadinessCheck {
    status: reqwest::StatusCode,
}

impl ReadinessCheck {
    fn summary(&self) -> &'static str {
        match self.status.as_u16() {
            200 => "reachable",
            401 => "reachable (token required or invalid)",
            403 => "reachable (source not allowed)",
            _ => "unexpected response",
        }
    }
}

async fn control_plane_readiness(
    client: &reqwest::Client,
    control_plane: &str,
    token: Option<&str>,
) -> Result<ReadinessCheck> {
    let url = format!("{}/internal/workers", control_plane.trim_end_matches('/'));
    let mut req = client.get(&url);
    if let Some(token) = token {
        req = req.header("X-Internal-Token", token);
    }
    let response = req
        .send()
        .await
        .with_context(|| format!("failed to reach control plane at {control_plane}"))?;
    Ok(ReadinessCheck {
        status: response.status(),
    })
}

struct EndpointStatus {
    ok: bool,
    detail: String,
}

impl EndpointStatus {
    fn summary(&self) -> &str {
        if self.ok { "ok" } else { &self.detail }
    }
}

async fn probe_health(client: &reqwest::Client, url: &str) -> EndpointStatus {
    match client.get(url).send().await {
        Ok(response) if response.status().is_success() => EndpointStatus {
            ok: true,
            detail: "ok".to_string(),
        },
        Ok(response) => EndpointStatus {
            ok: false,
            detail: format!("http {}", response.status()),
        },
        Err(err) => EndpointStatus {
            ok: false,
            detail: err.to_string(),
        },
    }
}

async fn probe_sglang(client: &reqwest::Client, sglang_url: &str) -> EndpointStatus {
    let health = probe_health(
        client,
        &format!("{}/health", sglang_url.trim_end_matches('/')),
    )
    .await;
    if !health.ok {
        return health;
    }
    match client
        .get(format!("{}/v1/models", sglang_url.trim_end_matches('/')))
        .send()
        .await
    {
        Ok(response) if response.status().is_success() => EndpointStatus {
            ok: true,
            detail: "ok".to_string(),
        },
        Ok(response) => EndpointStatus {
            ok: false,
            detail: format!("/v1/models http {}", response.status()),
        },
        Err(err) => EndpointStatus {
            ok: false,
            detail: err.to_string(),
        },
    }
}

#[derive(Clone, Debug, Default, serde::Deserialize)]
struct AgentCapabilities {
    llm: bool,
    embedding: bool,
    vision: bool,
}

#[derive(Clone, Debug, Default, serde::Deserialize)]
struct AgentHealth {
    #[serde(default)]
    status: String,
    #[serde(default)]
    backend: String,
    #[serde(default)]
    capabilities: AgentCapabilities,
    #[serde(default)]
    max_context: Option<u32>,
    #[serde(default)]
    inflight: usize,
    #[serde(default)]
    queue_depth: usize,
}

impl AgentHealth {
    fn is_ok(&self) -> bool {
        self.status.eq_ignore_ascii_case("ok")
    }

    fn is_idle(&self) -> bool {
        self.is_ok() && self.inflight == 0 && self.queue_depth == 0
    }
}

async fn probe_agent_health(client: &reqwest::Client, url: &str) -> AgentHealth {
    match client.get(url).send().await {
        Ok(response) => response.json().await.unwrap_or_default(),
        Err(_) => AgentHealth::default(),
    }
}

#[derive(serde::Deserialize)]
struct WorkerSnapshot {
    id: String,
    addr: String,
    backend: String,
    health: String,
    drain: bool,
}

async fn probe_registered_worker(
    client: &reqwest::Client,
    control_plane: &str,
    token: Option<&str>,
    advertised_addr: SocketAddr,
) -> Result<Option<WorkerSnapshot>> {
    let url = format!("{}/internal/workers", control_plane.trim_end_matches('/'));
    let mut req = client.get(&url);
    if let Some(token) = token {
        req = req.header("X-Internal-Token", token);
    }
    let response = req
        .send()
        .await
        .with_context(|| format!("failed to fetch worker list from {control_plane}"))?
        .error_for_status()
        .context("control plane rejected worker-list request")?;
    let workers: Vec<WorkerSnapshot> = response
        .json()
        .await
        .context("failed to parse control-plane worker list")?;
    Ok(workers
        .into_iter()
        .find(|worker| worker.addr == advertised_addr.to_string()))
}

fn runtime_base_url(env_file: &ThorEnvFile) -> String {
    env_file
        .get("AXS_THOR_RUNTIME_URL")
        .or_else(|| env_file.get("AXS_SGLANG_URL"))
        .unwrap_or(DEFAULT_SGLANG_URL)
        .trim_end_matches('/')
        .to_string()
}

fn resolve_worker_id(env_file: &ThorEnvFile) -> Option<String> {
    let path = env_file.get("AXS_THOR_WORKER_ID_PATH")?;
    std::fs::read_to_string(path)
        .ok()
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

fn expected_capabilities(backend: &str) -> AgentCapabilities {
    match backend {
        "sglang" => AgentCapabilities {
            llm: true,
            embedding: true,
            vision: false,
        },
        _ => AgentCapabilities::default(),
    }
}

struct ThorStatusReport {
    config_path: PathBuf,
    control_plane: String,
    control: ReadinessCheck,
    local_agent_base: String,
    thor: EndpointStatus,
    runtime_url: String,
    sglang: EndpointStatus,
    worker: Option<WorkerSnapshot>,
    config_mismatch: Option<&'static str>,
    overall_state: &'static str,
    ready: bool,
}

async fn collect_status_report(
    path: &Path,
    connect_timeout: std::time::Duration,
    request_timeout: std::time::Duration,
) -> Result<ThorStatusReport> {
    let env_file = ThorEnvFile::read(path)?;
    let control_plane = env_file
        .get("AXS_CONTROL_PLANE_URL")
        .context("AXS_CONTROL_PLANE_URL missing from thor config")?
        .to_string();
    let listen_addr_raw = env_file
        .get("AXS_THOR_LISTEN_ADDR")
        .unwrap_or(DEFAULT_THOR_LISTEN_ADDR);
    let advertised_addr_raw = env_file
        .get("AXS_THOR_ADVERTISED_ADDR")
        .unwrap_or(listen_addr_raw);
    let listen_addr = parse_socket_addr(listen_addr_raw, "listen address")?;
    let advertised_addr = parse_socket_addr(advertised_addr_raw, "advertised address")?;
    let local_agent_base = local_probe_base(listen_addr);
    let runtime_url = runtime_base_url(&env_file);
    let expected_backend = env_file.get("AXS_THOR_BACKEND").unwrap_or("sglang");
    let expected_max_context = env_file
        .get("AXS_THOR_MAX_CONTEXT")
        .and_then(|v| v.parse::<u32>().ok());
    let expected_worker_id = resolve_worker_id(&env_file);

    let client = reqwest::Client::builder()
        .connect_timeout(connect_timeout)
        .timeout(request_timeout)
        .build()
        .context("failed to build HTTP client for thor status")?;

    let token = env_file.get("AXS_WORKER_TOKEN");
    let thor_health_url = format!("{local_agent_base}/health");
    let (control, sglang, thor, agent_health, worker) = tokio::join!(
        control_plane_readiness(&client, &control_plane, token),
        probe_sglang(&client, &runtime_url),
        probe_health(&client, &thor_health_url),
        probe_agent_health(&client, &thor_health_url),
        probe_registered_worker(&client, &control_plane, token, advertised_addr),
    );
    let control = control?;
    let worker = worker?;

    let config_mismatch = if !agent_health.backend.is_empty()
        && agent_health.backend != expected_backend
    {
        Some("backend_mismatch")
    } else if agent_health.capabilities.llm != expected_capabilities(expected_backend).llm
        || agent_health.capabilities.embedding != expected_capabilities(expected_backend).embedding
        || agent_health.capabilities.vision != expected_capabilities(expected_backend).vision
    {
        Some("capability_mismatch")
    } else if expected_max_context.is_some() && agent_health.max_context != expected_max_context {
        Some("max_context_mismatch")
    } else {
        None
    };

    let registration_ok = match (&worker, expected_worker_id.as_deref()) {
        (Some(worker), Some(expected_id)) => worker.id == expected_id,
        (Some(_), None) => true,
        _ => false,
    };

    let ready = control.status == reqwest::StatusCode::OK
        && thor.ok
        && sglang.ok
        && registration_ok
        && config_mismatch.is_none()
        && worker
            .as_ref()
            .is_some_and(|worker| worker.health == "healthy" && !worker.drain);

    let overall_state = if ready {
        "ready"
    } else if !registration_ok || config_mismatch.is_some() {
        "registration_mismatch"
    } else if !thor.ok || !sglang.ok {
        "local_unhealthy"
    } else {
        "not_ready"
    };

    Ok(ThorStatusReport {
        config_path: path.to_path_buf(),
        control_plane,
        control,
        local_agent_base,
        thor,
        runtime_url,
        sglang,
        worker,
        config_mismatch,
        overall_state,
        ready,
    })
}

fn print_status_report(report: &ThorStatusReport) {
    println!("config: {}", report.config_path.display());
    println!(
        "control plane: {} ({})",
        report.control_plane,
        report.control.summary()
    );
    println!(
        "thor agent: {} ({})",
        report.local_agent_base,
        report.thor.summary()
    );
    println!(
        "sglang: {} ({})",
        report.runtime_url,
        report.sglang.summary()
    );
    match &report.worker {
        Some(worker) => println!(
            "registry: registered as {} backend={} health={} drain={}",
            worker.id, worker.backend, worker.health, worker.drain
        ),
        None => println!("registry: no worker currently registered"),
    }
    if let Some(reason) = report.config_mismatch {
        println!("thor agent config: {reason}");
    }
    println!("overall_state={}", report.overall_state);
}

fn fallback_status_report(path: &Path) -> Result<ThorStatusReport> {
    let env_file = ThorEnvFile::read(path)?;
    fallback_status_report_from_env(path.to_path_buf(), &env_file)
}

fn fallback_status_report_from_env(
    path: PathBuf,
    env_file: &ThorEnvFile,
) -> Result<ThorStatusReport> {
    let control_plane = env_file
        .get("AXS_CONTROL_PLANE_URL")
        .unwrap_or("<missing>")
        .to_string();
    let listen_addr = env_file
        .get("AXS_THOR_LISTEN_ADDR")
        .unwrap_or(DEFAULT_THOR_LISTEN_ADDR);
    let local_agent_base = local_probe_base(parse_socket_addr(listen_addr, "listen address")?);
    Ok(ThorStatusReport {
        config_path: path,
        control_plane,
        control: ReadinessCheck {
            status: reqwest::StatusCode::REQUEST_TIMEOUT,
        },
        local_agent_base,
        thor: EndpointStatus {
            ok: false,
            detail: "timeout".to_string(),
        },
        runtime_url: runtime_base_url(env_file),
        sglang: EndpointStatus {
            ok: false,
            detail: "timeout".to_string(),
        },
        worker: None,
        config_mismatch: None,
        overall_state: "registration_mismatch",
        ready: false,
    })
}

async fn post_control_plane_action(
    client: &reqwest::Client,
    control_plane: &str,
    token: Option<&str>,
    worker_id: &str,
    action: &str,
) -> Result<()> {
    let url = format!(
        "{}/internal/workers/{worker_id}/{action}",
        control_plane.trim_end_matches('/')
    );
    let mut req = client.post(url);
    if let Some(token) = token {
        req = req.header("X-Internal-Token", token);
    }
    req.send()
        .await
        .with_context(|| format!("thor {action} request failed"))?
        .error_for_status()
        .with_context(|| format!("thor {action} request rejected"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{ThorEnvFile, local_probe_base, parse_socket_addr};

    #[test]
    fn local_probe_base_rewrites_unspecified_ipv4() {
        let addr = parse_socket_addr("0.0.0.0:18081", "listen").unwrap();
        assert_eq!(local_probe_base(addr), "http://127.0.0.1:18081");
    }

    #[test]
    fn env_file_set_removes_empty_values() {
        let mut env_file = ThorEnvFile::default();
        env_file.set(
            "AXS_CONTROL_PLANE_URL",
            Some("http://127.0.0.1:19090".into()),
        );
        env_file.set("AXS_CONTROL_PLANE_URL", Some(String::new()));
        assert!(env_file.get("AXS_CONTROL_PLANE_URL").is_none());
    }

    #[test]
    fn env_file_set_if_some_preserves_existing_value() {
        let mut env_file = ThorEnvFile::default();
        env_file.set("AXS_WORKER_TOKEN", Some("secret".into()));
        env_file.set_if_some("AXS_WORKER_TOKEN", None);
        assert_eq!(env_file.get("AXS_WORKER_TOKEN"), Some("secret"));
    }
}
