use std::collections::BTreeMap;
use std::io::Write;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};

const THOR_ENV_KEYS: &[&str] = &[
    "AXS_CONTROL_PLANE_URL",
    "AXS_WORKER_TOKEN",
    "AXS_SGLANG_URL",
    "AXS_THOR_LISTEN_ADDR",
    "AXS_THOR_ADVERTISED_ADDR",
    "AXS_THOR_MAX_INFLIGHT",
    "AXS_THOR_WORKER_POOL",
    "AXS_THOR_NODE_CLASS",
    "AXS_THOR_FRIENDLY_NAME",
    "AXS_THOR_CHIP_MODEL",
];

pub struct InstallArgs {
    pub control_plane: Option<String>,
    pub listen_addr: String,
    pub advertised_addr: Option<String>,
    pub sglang_url: String,
    pub worker_token: Option<String>,
    pub max_inflight: usize,
    pub worker_pool: Option<String>,
    pub node_class: String,
    pub friendly_name: Option<String>,
    pub chip_model: Option<String>,
    pub output: Option<PathBuf>,
}

pub struct JoinArgs {
    pub control_plane: String,
    pub advertised_addr: Option<String>,
    pub listen_addr: Option<String>,
    pub sglang_url: Option<String>,
    pub worker_token: Option<String>,
    pub max_inflight: Option<usize>,
    pub worker_pool: Option<String>,
    pub node_class: Option<String>,
    pub friendly_name: Option<String>,
    pub chip_model: Option<String>,
    pub output: Option<PathBuf>,
}

pub struct StatusArgs {
    pub config: Option<PathBuf>,
}

#[derive(Clone, Debug, Default)]
struct ThorEnvFile {
    values: BTreeMap<String, String>,
}

impl ThorEnvFile {
    fn read(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        let mut values = BTreeMap::new();
        for raw_line in content.lines() {
            let line = raw_line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                continue;
            };
            values.insert(key.trim().to_string(), value.trim().to_string());
        }
        Ok(Self { values })
    }

    fn write(&self, path: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("failed to create {}", parent.display()))?;
        }

        let mut file = std::fs::File::create(path)
            .with_context(|| format!("failed to write {}", path.display()))?;
        writeln!(file, "# ax-thor-agent environment file")?;
        writeln!(file, "# generated by `ax-serving thor`")?;
        for key in THOR_ENV_KEYS {
            if let Some(value) = self.values.get(*key) {
                writeln!(file, "{key}={value}")?;
            }
        }
        Ok(())
    }

    fn set(&mut self, key: &str, value: Option<String>) {
        match value {
            Some(value) if !value.trim().is_empty() => {
                self.values.insert(key.to_string(), value.trim().to_string());
            }
            _ => {
                self.values.remove(key);
            }
        }
    }

    fn get(&self, key: &str) -> Option<&str> {
        self.values.get(key).map(String::as_str)
    }

    fn set_if_some(&mut self, key: &str, value: Option<String>) {
        if let Some(value) = value {
            self.set(key, Some(value));
        }
    }
}

pub fn install(args: InstallArgs) -> Result<()> {
    let path = args.output.unwrap_or_else(default_thor_env_path);
    let listen_addr = parse_socket_addr(&args.listen_addr, "listen address")?;
    let advertised_addr = parse_socket_addr(
        args.advertised_addr.as_deref().unwrap_or(&args.listen_addr),
        "advertised address",
    )?;

    let mut env_file = if path.exists() {
        ThorEnvFile::read(&path)?
    } else {
        ThorEnvFile::default()
    };

    env_file.set(
        "AXS_CONTROL_PLANE_URL",
        args.control_plane.map(trim_trailing_slash),
    );
    env_file.set("AXS_SGLANG_URL", Some(trim_trailing_slash(args.sglang_url)));
    env_file.set("AXS_WORKER_TOKEN", args.worker_token);
    env_file.set("AXS_THOR_LISTEN_ADDR", Some(listen_addr.to_string()));
    env_file.set("AXS_THOR_ADVERTISED_ADDR", Some(advertised_addr.to_string()));
    env_file.set("AXS_THOR_MAX_INFLIGHT", Some(args.max_inflight.max(1).to_string()));
    env_file.set("AXS_THOR_WORKER_POOL", args.worker_pool);
    env_file.set("AXS_THOR_NODE_CLASS", Some(args.node_class));
    env_file.set("AXS_THOR_FRIENDLY_NAME", args.friendly_name);
    env_file.set("AXS_THOR_CHIP_MODEL", args.chip_model);
    env_file.write(&path)?;

    print_preflight(&path, &env_file);
    Ok(())
}

pub async fn join(args: JoinArgs) -> Result<()> {
    let path = args.output.unwrap_or_else(default_thor_env_path);
    let mut env_file = if path.exists() {
        ThorEnvFile::read(&path)?
    } else {
        ThorEnvFile::default()
    };

    env_file.set(
        "AXS_CONTROL_PLANE_URL",
        Some(trim_trailing_slash(args.control_plane)),
    );
    env_file.set_if_some("AXS_WORKER_TOKEN", args.worker_token);
    env_file.set_if_some("AXS_SGLANG_URL", args.sglang_url.map(trim_trailing_slash));
    if let Some(listen_addr) = args.listen_addr {
        let listen_addr = parse_socket_addr(&listen_addr, "listen address")?;
        env_file.set("AXS_THOR_LISTEN_ADDR", Some(listen_addr.to_string()));
    }
    if let Some(advertised_addr) = args.advertised_addr {
        let advertised_addr = parse_socket_addr(&advertised_addr, "advertised address")?;
        env_file.set("AXS_THOR_ADVERTISED_ADDR", Some(advertised_addr.to_string()));
    }
    if let Some(max_inflight) = args.max_inflight {
        env_file.set("AXS_THOR_MAX_INFLIGHT", Some(max_inflight.max(1).to_string()));
    }
    env_file.set_if_some("AXS_THOR_WORKER_POOL", args.worker_pool);
    env_file.set_if_some("AXS_THOR_NODE_CLASS", args.node_class);
    env_file.set_if_some("AXS_THOR_FRIENDLY_NAME", args.friendly_name);
    env_file.set_if_some("AXS_THOR_CHIP_MODEL", args.chip_model);

    let control_plane = env_file
        .get("AXS_CONTROL_PLANE_URL")
        .context("AXS_CONTROL_PLANE_URL is required")?;
    let worker_token = env_file.get("AXS_WORKER_TOKEN").map(str::to_string);
    let listen_addr = env_file
        .get("AXS_THOR_LISTEN_ADDR")
        .unwrap_or("0.0.0.0:18081");
    parse_socket_addr(listen_addr, "listen address")?;
    let advertised_addr = env_file
        .get("AXS_THOR_ADVERTISED_ADDR")
        .unwrap_or(listen_addr);
    parse_socket_addr(advertised_addr, "advertised address")?;

    let client = reqwest::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(3))
        .timeout(std::time::Duration::from_secs(5))
        .build()
        .context("failed to build HTTP client for join check")?;
    let check = control_plane_readiness(&client, control_plane, worker_token.as_deref()).await?;

    env_file.write(&path)?;
    println!("thor config updated: {}", path.display());
    println!("control plane: {}", control_plane);
    println!("readiness: {}", check.summary());
    println!(
        "next: run `ax-thor-agent` with env from {}",
        path.display()
    );
    Ok(())
}

pub async fn status(args: StatusArgs) -> Result<()> {
    let path = args.config.unwrap_or_else(default_thor_env_path);
    let env_file = ThorEnvFile::read(&path)?;

    let control_plane = env_file
        .get("AXS_CONTROL_PLANE_URL")
        .context("AXS_CONTROL_PLANE_URL missing from thor config")?;
    let sglang_url = env_file
        .get("AXS_SGLANG_URL")
        .unwrap_or("http://127.0.0.1:30000");
    let listen_addr = env_file
        .get("AXS_THOR_LISTEN_ADDR")
        .unwrap_or("0.0.0.0:18081");
    let advertised_addr = env_file
        .get("AXS_THOR_ADVERTISED_ADDR")
        .unwrap_or(listen_addr);
    let listen_addr = parse_socket_addr(listen_addr, "listen address")?;
    let advertised_addr = parse_socket_addr(advertised_addr, "advertised address")?;
    let local_agent_base = local_probe_base(listen_addr);

    let client = reqwest::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(3))
        .timeout(std::time::Duration::from_secs(5))
        .build()
        .context("failed to build HTTP client for thor status")?;

    let control = control_plane_readiness(
        &client,
        control_plane,
        env_file.get("AXS_WORKER_TOKEN"),
    )
    .await?;
    let sglang = probe_sglang(&client, sglang_url).await;
    let thor = probe_health(&client, &format!("{local_agent_base}/health")).await;
    let worker = probe_registered_worker(
        &client,
        control_plane,
        env_file.get("AXS_WORKER_TOKEN"),
        advertised_addr,
    )
    .await;

    println!("config: {}", path.display());
    println!("control plane: {} ({})", control_plane, control.summary());
    println!("thor agent: {} ({})", local_agent_base, thor.summary());
    println!("sglang: {} ({})", sglang_url, sglang.summary());
    match worker {
        Ok(Some(worker)) => {
            println!(
                "registry: registered as {} backend={} health={} drain={}",
                worker.id, worker.backend, worker.health, worker.drain
            );
        }
        Ok(None) => {
            println!(
                "registry: no worker currently registered for {}",
                advertised_addr
            );
        }
        Err(err) => {
            println!("registry: unavailable ({err})");
        }
    }

    Ok(())
}

fn default_thor_env_path() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config/ax-serving/thor.env")
}

fn trim_trailing_slash(input: String) -> String {
    input.trim().trim_end_matches('/').to_string()
}

fn parse_socket_addr(raw: &str, label: &str) -> Result<SocketAddr> {
    raw.parse()
        .with_context(|| format!("invalid {label}: '{raw}'"))
}

fn local_probe_base(listen_addr: SocketAddr) -> String {
    let ip = match listen_addr.ip() {
        IpAddr::V4(ip) if ip.is_unspecified() => IpAddr::V4(Ipv4Addr::LOCALHOST),
        IpAddr::V6(ip) if ip.is_unspecified() => IpAddr::V6(std::net::Ipv6Addr::LOCALHOST),
        ip => ip,
    };
    format!("http://{}:{}", ip, listen_addr.port())
}

fn print_preflight(path: &Path, env_file: &ThorEnvFile) {
    println!("thor config written: {}", path.display());
    println!(
        "control plane: {}",
        env_file.get("AXS_CONTROL_PLANE_URL").unwrap_or("<unset>")
    );
    println!(
        "listen addr: {}",
        env_file
            .get("AXS_THOR_LISTEN_ADDR")
            .unwrap_or("0.0.0.0:18081")
    );
    println!(
        "advertised addr: {}",
        env_file
            .get("AXS_THOR_ADVERTISED_ADDR")
            .unwrap_or("0.0.0.0:18081")
    );

    let docker = check_command("docker", &["--version"]);
    let cargo = check_command("cargo", &["--version"]);
    println!("docker: {}", docker);
    println!("cargo: {}", cargo);
    println!(
        "next: run `ax-serving thor join --control-plane <url>` and then launch `ax-thor-agent` with env from {}",
        path.display()
    );
}

fn check_command(program: &str, args: &[&str]) -> &'static str {
    match Command::new(program).args(args).output() {
        Ok(output) if output.status.success() => "ok",
        Ok(_) => "present but failing",
        Err(_) => "missing",
    }
}

struct ReadinessCheck {
    status: reqwest::StatusCode,
}

impl ReadinessCheck {
    fn summary(&self) -> &'static str {
        match self.status.as_u16() {
            200 => "reachable",
            401 => "reachable (token required or invalid)",
            403 => "reachable (source not allowed)",
            _ => "unexpected response",
        }
    }
}

async fn control_plane_readiness(
    client: &reqwest::Client,
    control_plane: &str,
    token: Option<&str>,
) -> Result<ReadinessCheck> {
    let url = format!("{}/internal/workers", control_plane.trim_end_matches('/'));
    let mut req = client.get(&url);
    if let Some(token) = token {
        req = req.header("X-Internal-Token", token);
    }
    let response = req
        .send()
        .await
        .with_context(|| format!("failed to reach control plane at {control_plane}"))?;
    Ok(ReadinessCheck {
        status: response.status(),
    })
}

struct EndpointStatus {
    ok: bool,
    detail: String,
}

impl EndpointStatus {
    fn summary(&self) -> &str {
        if self.ok { "ok" } else { &self.detail }
    }
}

async fn probe_health(client: &reqwest::Client, url: &str) -> EndpointStatus {
    match client.get(url).send().await {
        Ok(response) if response.status().is_success() => EndpointStatus {
            ok: true,
            detail: "ok".to_string(),
        },
        Ok(response) => EndpointStatus {
            ok: false,
            detail: format!("http {}", response.status()),
        },
        Err(err) => EndpointStatus {
            ok: false,
            detail: err.to_string(),
        },
    }
}

async fn probe_sglang(client: &reqwest::Client, sglang_url: &str) -> EndpointStatus {
    let health = probe_health(client, &format!("{}/health", sglang_url.trim_end_matches('/'))).await;
    if !health.ok {
        return health;
    }
    match client
        .get(format!("{}/v1/models", sglang_url.trim_end_matches('/')))
        .send()
        .await
    {
        Ok(response) if response.status().is_success() => EndpointStatus {
            ok: true,
            detail: "ok".to_string(),
        },
        Ok(response) => EndpointStatus {
            ok: false,
            detail: format!("/v1/models http {}", response.status()),
        },
        Err(err) => EndpointStatus {
            ok: false,
            detail: err.to_string(),
        },
    }
}

#[derive(serde::Deserialize)]
struct WorkerSnapshot {
    id: String,
    addr: String,
    backend: String,
    health: String,
    drain: bool,
}

async fn probe_registered_worker(
    client: &reqwest::Client,
    control_plane: &str,
    token: Option<&str>,
    advertised_addr: SocketAddr,
) -> Result<Option<WorkerSnapshot>> {
    let url = format!("{}/internal/workers", control_plane.trim_end_matches('/'));
    let mut req = client.get(&url);
    if let Some(token) = token {
        req = req.header("X-Internal-Token", token);
    }
    let response = req
        .send()
        .await
        .with_context(|| format!("failed to fetch worker list from {control_plane}"))?
        .error_for_status()
        .context("control plane rejected worker-list request")?;
    let workers: Vec<WorkerSnapshot> = response
        .json()
        .await
        .context("failed to parse control-plane worker list")?;
    Ok(workers
        .into_iter()
        .find(|worker| worker.addr == advertised_addr.to_string()))
}

#[cfg(test)]
mod tests {
    use super::{ThorEnvFile, local_probe_base, parse_socket_addr};

    #[test]
    fn local_probe_base_rewrites_unspecified_ipv4() {
        let addr = parse_socket_addr("0.0.0.0:18081", "listen").unwrap();
        assert_eq!(local_probe_base(addr), "http://127.0.0.1:18081");
    }

    #[test]
    fn env_file_set_removes_empty_values() {
        let mut env_file = ThorEnvFile::default();
        env_file.set("AXS_CONTROL_PLANE_URL", Some("http://127.0.0.1:19090".into()));
        env_file.set("AXS_CONTROL_PLANE_URL", Some(String::new()));
        assert!(env_file.get("AXS_CONTROL_PLANE_URL").is_none());
    }

    #[test]
    fn env_file_set_if_some_preserves_existing_value() {
        let mut env_file = ThorEnvFile::default();
        env_file.set("AXS_WORKER_TOKEN", Some("secret".into()));
        env_file.set_if_some("AXS_WORKER_TOKEN", None);
        assert_eq!(env_file.get("AXS_WORKER_TOKEN"), Some("secret"));
    }
}
