//! `ax-serving tune` — detect hardware and emit recommended serving config.

use std::path::PathBuf;
use std::process::Command;

use anyhow::{Context, Result};

/// Hardware profile detected from the local machine.
#[derive(Debug)]
pub struct HardwareProfile {
    pub chip_model: String,
    pub performance_cores: usize,
    pub efficiency_cores: usize,
    pub total_memory_gb: u64,
    pub os_version: String,
}

impl HardwareProfile {
    pub fn detect() -> Result<Self> {
        let chip_model = detect_chip_model().unwrap_or_else(|| "Unknown".into());
        let (performance_cores, efficiency_cores) = detect_core_counts();
        let total_memory_gb = detect_memory_gb();
        let os_version = detect_os_version().unwrap_or_else(|| "Unknown".into());

        Ok(Self {
            chip_model,
            performance_cores,
            efficiency_cores,
            total_memory_gb,
            os_version,
        })
    }

    /// Determine the recommended SKU class for tuning defaults.
    pub fn sku_class(&self) -> SkuClass {
        let chip = self.chip_model.to_lowercase();
        if chip.contains("ultra") {
            SkuClass::Ultra
        } else if chip.contains("max") {
            SkuClass::Max
        } else if chip.contains("pro") {
            SkuClass::Pro
        } else {
            SkuClass::Base
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkuClass {
    Base,
    Pro,
    Max,
    Ultra,
}

impl SkuClass {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Base => "base",
            Self::Pro => "pro",
            Self::Max => "max",
            Self::Ultra => "ultra",
        }
    }
}

/// Recommended serving configuration derived from hardware profile.
#[derive(Debug)]
pub struct TuneRecommendation {
    pub sched_max_inflight: usize,
    pub sched_max_queue: usize,
    pub sched_max_wait_ms: u64,
    pub sched_per_model_max_inflight: usize,
    pub sched_max_prefill_tokens: u64,
    pub default_max_tokens: u32,
    pub sku_class: SkuClass,
}

impl TuneRecommendation {
    /// Generate recommendation from hardware profile.
    ///
    /// Based on the per-SKU tuning table in docs/perf/service-tuning.md:
    /// | SKU        | max_inflight | max_queue | max_wait_ms |
    /// |------------|-------------|-----------|-------------|
    /// | M3/M3 Air  | 4           | 24        | 150         |
    /// | M3 Pro     | 8           | 64        | 250         |
    /// | M3 Max     | 12          | 96        | 300         |
    /// | M3 Ultra   | 16          | 128       | 400         |
    pub fn from_profile(profile: &HardwareProfile) -> Self {
        match profile.sku_class() {
            SkuClass::Base => Self {
                sched_max_inflight: 4,
                sched_max_queue: 24,
                sched_max_wait_ms: 150,
                sched_per_model_max_inflight: 2,
                sched_max_prefill_tokens: 2048,
                default_max_tokens: 2048,
                sku_class: SkuClass::Base,
            },
            SkuClass::Pro => Self {
                sched_max_inflight: 8,
                sched_max_queue: 64,
                sched_max_wait_ms: 250,
                sched_per_model_max_inflight: 4,
                sched_max_prefill_tokens: 4096,
                default_max_tokens: 2048,
                sku_class: SkuClass::Pro,
            },
            SkuClass::Max => Self {
                sched_max_inflight: 12,
                sched_max_queue: 96,
                sched_max_wait_ms: 300,
                sched_per_model_max_inflight: 6,
                sched_max_prefill_tokens: 8192,
                default_max_tokens: 4096,
                sku_class: SkuClass::Max,
            },
            SkuClass::Ultra => Self {
                sched_max_inflight: 16,
                sched_max_queue: 128,
                sched_max_wait_ms: 400,
                sched_per_model_max_inflight: 8,
                sched_max_prefill_tokens: 16384,
                default_max_tokens: 4096,
                sku_class: SkuClass::Ultra,
            },
        }
    }

    /// Render the recommendation as a TOML config file.
    pub fn to_toml(&self, profile: &HardwareProfile) -> String {
        format!(
            r#"# AX Serving configuration — auto-generated by `ax-serving tune`
# Hardware: {chip} ({memory} GB, {perf}P+{eff}E cores)
# SKU class: {sku}
# Date: {date}
#
# Review and adjust these values based on your workload.
# See docs/perf/service-tuning.md for detailed tuning guidance.

# ── Admission scheduler ──────────────────────────────────────────────────────

# Max concurrent inference requests (tune down if thermals spike).
sched_max_inflight = {max_inflight}

# Max requests waiting in the admission queue.
sched_max_queue = {max_queue}

# Max time (ms) a request waits in the queue before timeout (503).
sched_max_wait_ms = {max_wait_ms}

# Per-model concurrency cap (each model ID gets its own semaphore).
sched_per_model_max_inflight = {per_model}

# Max concurrent prompt tokens in the prefill phase (split scheduler).
sched_max_prefill_tokens = {prefill_tokens}

# Default max_tokens when the client omits the field.
default_max_tokens = {default_tokens}

# ── Overload policy ──────────────────────────────────────────────────────────

# "queue" = queue up to max_queue then reject with 429.
# "shed_oldest" = drop oldest waiter when full.
sched_overload_policy = "queue"
"#,
            chip = profile.chip_model,
            memory = profile.total_memory_gb,
            perf = profile.performance_cores,
            eff = profile.efficiency_cores,
            sku = self.sku_class.as_str(),
            date = chrono_date(),
            max_inflight = self.sched_max_inflight,
            max_queue = self.sched_max_queue,
            max_wait_ms = self.sched_max_wait_ms,
            per_model = self.sched_per_model_max_inflight,
            prefill_tokens = self.sched_max_prefill_tokens,
            default_tokens = self.default_max_tokens,
        )
    }
}

pub fn run_tune(output: Option<PathBuf>, dry_run: bool) -> Result<()> {
    let profile = HardwareProfile::detect()?;
    eprintln!("Hardware detected:");
    eprintln!("  Chip:    {}", profile.chip_model);
    eprintln!(
        "  Cores:   {}P + {}E",
        profile.performance_cores, profile.efficiency_cores
    );
    eprintln!("  Memory:  {} GB", profile.total_memory_gb);
    eprintln!("  OS:      {}", profile.os_version);
    eprintln!("  SKU:     {}", profile.sku_class().as_str());
    eprintln!();

    let rec = TuneRecommendation::from_profile(&profile);
    let toml = rec.to_toml(&profile);

    if dry_run {
        eprintln!("Recommended configuration (dry-run, not writing):\n");
        println!("{toml}");
        return Ok(());
    }

    let explicit_output = output.is_some();
    let path = output.unwrap_or_else(|| PathBuf::from("serving.toml"));
    if path.exists() && !explicit_output {
        eprintln!(
            "Warning: {} already exists. Writing to serving.tune.toml instead.",
            path.display()
        );
        let alt = PathBuf::from("serving.tune.toml");
        std::fs::write(&alt, &toml).context("failed to write serving.tune.toml")?;
        eprintln!("Wrote recommended config to {}", alt.display());
    } else {
        std::fs::write(&path, &toml)
            .with_context(|| format!("failed to write {}", path.display()))?;
        eprintln!("Wrote recommended config to {}", path.display());
    }

    Ok(())
}

// ── Hardware detection helpers ───────────────────────────────────────────────

fn detect_chip_model() -> Option<String> {
    // Apple Silicon exposes chip info via system_profiler (not sysctl).
    let output = Command::new("system_profiler")
        .args(["SPHardwareDataType"])
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&output.stdout);
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("Chip:") {
            return Some(trimmed.trim_start_matches("Chip:").trim().to_string());
        }
    }
    None
}

fn detect_core_counts() -> (usize, usize) {
    let perf = sysctl_usize("hw.perflevel0.logicalcpu").unwrap_or(0);
    let eff = sysctl_usize("hw.perflevel1.logicalcpu").unwrap_or(0);
    if perf > 0 {
        (perf, eff)
    } else {
        let total = sysctl_usize("hw.logicalcpu").unwrap_or(4);
        (total, 0)
    }
}

fn detect_memory_gb() -> u64 {
    let gb = sysctl_u64("hw.memsize").unwrap_or(0) / (1024 * 1024 * 1024);
    if gb == 0 {
        eprintln!("WARNING: could not detect system memory; assuming 8 GB");
        return 8;
    }
    gb
}

fn detect_os_version() -> Option<String> {
    let output = Command::new("sw_vers")
        .args(["-productVersion"])
        .output()
        .ok()?;
    if output.status.success() {
        Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        None
    }
}

fn sysctl_usize(key: &str) -> Option<usize> {
    let output = Command::new("sysctl").args(["-n", key]).output().ok()?;
    if output.status.success() {
        String::from_utf8_lossy(&output.stdout).trim().parse().ok()
    } else {
        None
    }
}

fn sysctl_u64(key: &str) -> Option<u64> {
    let output = Command::new("sysctl").args(["-n", key]).output().ok()?;
    if output.status.success() {
        String::from_utf8_lossy(&output.stdout).trim().parse().ok()
    } else {
        None
    }
}

fn chrono_date() -> String {
    // Simple date without chrono dependency — use /bin/date
    Command::new("date")
        .args(["+%Y-%m-%d"])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
            } else {
                None
            }
        })
        .unwrap_or_else(|| "unknown".into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sku_class_detection() {
        let mut p = HardwareProfile {
            chip_model: "Apple M3 Pro".into(),
            performance_cores: 6,
            efficiency_cores: 6,
            total_memory_gb: 36,
            os_version: "15.3".into(),
        };
        assert_eq!(p.sku_class(), SkuClass::Pro);

        p.chip_model = "Apple M4 Max".into();
        assert_eq!(p.sku_class(), SkuClass::Max);

        p.chip_model = "Apple M3 Ultra".into();
        assert_eq!(p.sku_class(), SkuClass::Ultra);

        p.chip_model = "Apple M3".into();
        assert_eq!(p.sku_class(), SkuClass::Base);
    }

    #[test]
    fn recommendation_from_profile() {
        let profile = HardwareProfile {
            chip_model: "Apple M3 Max".into(),
            performance_cores: 12,
            efficiency_cores: 4,
            total_memory_gb: 64,
            os_version: "15.3".into(),
        };
        let rec = TuneRecommendation::from_profile(&profile);
        assert_eq!(rec.sched_max_inflight, 12);
        assert_eq!(rec.sched_max_queue, 96);
        assert_eq!(rec.sched_max_wait_ms, 300);
        assert_eq!(rec.sku_class, SkuClass::Max);
    }

    #[test]
    fn toml_output_contains_key_values() {
        let profile = HardwareProfile {
            chip_model: "Apple M3 Pro".into(),
            performance_cores: 6,
            efficiency_cores: 6,
            total_memory_gb: 36,
            os_version: "15.3".into(),
        };
        let rec = TuneRecommendation::from_profile(&profile);
        let toml = rec.to_toml(&profile);
        assert!(toml.contains("sched_max_inflight = 8"));
        assert!(toml.contains("sched_max_queue = 64"));
        assert!(toml.contains("Apple M3 Pro"));
    }
}
