# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ax_serving_pb2 as ax__serving__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ax_serving_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AxServingServiceStub(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/ax.serving.v1.AxServingService/LoadModel',
                request_serializer=ax__serving__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=ax__serving__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/ax.serving.v1.AxServingService/UnloadModel',
                request_serializer=ax__serving__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=ax__serving__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/ax.serving.v1.AxServingService/ListModels',
                request_serializer=ax__serving__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=ax__serving__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_stream(
                '/ax.serving.v1.AxServingService/Infer',
                request_serializer=ax__serving__pb2.InferRequest.SerializeToString,
                response_deserializer=ax__serving__pb2.InferResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ax.serving.v1.AxServingService/Health',
                request_serializer=ax__serving__pb2.HealthRequest.SerializeToString,
                response_deserializer=ax__serving__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/ax.serving.v1.AxServingService/GetMetrics',
                request_serializer=ax__serving__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=ax__serving__pb2.GetMetricsResponse.FromString,
                _registered_method=True)


class AxServingServiceServicer(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AxServingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=ax__serving__pb2.LoadModelRequest.FromString,
                    response_serializer=ax__serving__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=ax__serving__pb2.UnloadModelRequest.FromString,
                    response_serializer=ax__serving__pb2.UnloadModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=ax__serving__pb2.ListModelsRequest.FromString,
                    response_serializer=ax__serving__pb2.ListModelsResponse.SerializeToString,
            ),
            'Infer': grpc.unary_stream_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=ax__serving__pb2.InferRequest.FromString,
                    response_serializer=ax__serving__pb2.InferResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ax__serving__pb2.HealthRequest.FromString,
                    response_serializer=ax__serving__pb2.HealthResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=ax__serving__pb2.GetMetricsRequest.FromString,
                    response_serializer=ax__serving__pb2.GetMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ax.serving.v1.AxServingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ax.serving.v1.AxServingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AxServingService(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.serving.v1.AxServingService/LoadModel',
            ax__serving__pb2.LoadModelRequest.SerializeToString,
            ax__serving__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.serving.v1.AxServingService/UnloadModel',
            ax__serving__pb2.UnloadModelRequest.SerializeToString,
            ax__serving__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.serving.v1.AxServingService/ListModels',
            ax__serving__pb2.ListModelsRequest.SerializeToString,
            ax__serving__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ax.serving.v1.AxServingService/Infer',
            ax__serving__pb2.InferRequest.SerializeToString,
            ax__serving__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.serving.v1.AxServingService/Health',
            ax__serving__pb2.HealthRequest.SerializeToString,
            ax__serving__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ax.serving.v1.AxServingService/GetMetrics',
            ax__serving__pb2.GetMetricsRequest.SerializeToString,
            ax__serving__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
