/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#ifndef LLAMA_H
#define LLAMA_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Opaque handle types ──────────────────────────────────────────────────── */

/**
 * Opaque model handle. Never dereference — always pass by pointer.
 */
typedef struct llama_model llama_model;

/**
 * Opaque inference context handle. Never dereference — always pass by pointer.
 */
typedef struct llama_context llama_context;

/**
 * Token ID type. Matches llama.cpp ABI (signed 32-bit integer).
 */
typedef int32_t llama_token;

/* ── Structs ─────────────────────────────────────────────────────────────── */

/**
 * Parameters for loading a model (mirrors llama_model_params).
 */
typedef struct llama_model_params {
    /** Number of GPU layers (-1 = all, 0 = CPU only). */
    int32_t n_gpu_layers;
    /** Context length override (0 = use model default). */
    uint32_t n_ctx;
    /** Reserved / ignored. */
    uint32_t _pad[6];
} llama_model_params;

/**
 * Parameters for creating a context (mirrors llama_context_params).
 */
typedef struct llama_context_params {
    uint32_t n_ctx;
    uint32_t seed;
    uint32_t _pad[6];
} llama_context_params;

/**
 * Token data entry (mirrors llama_token_data).
 */
typedef struct llama_token_data {
    llama_token id;
    float logit;
    float p;
} llama_token_data;

/**
 * Candidate array (mirrors llama_token_data_array).
 */
typedef struct llama_token_data_array {
    llama_token_data *data;
    size_t size;
    int64_t selected;
    bool sorted;
} llama_token_data_array;

/* ── Backend init / free ─────────────────────────────────────────────────── */

/**
 * Initialize the inference backend. Must be called before any other function.
 * `numa` is ignored (Apple Silicon has no NUMA topology).
 */
void llama_backend_init(bool numa);

/**
 * Free backend resources. No-op in ax-serving (resources freed on drop).
 */
void llama_backend_free(void);

/**
 * Return current wall-clock time in microseconds since UNIX epoch.
 * Matches llama.cpp's llama_time_us() for benchmarking elapsed time.
 */
int64_t llama_time_us(void);

/**
 * Return a null-terminated string describing the inference backend.
 * The returned pointer is static — never free it.
 */
const char *llama_system_info(void);

/* ── Model lifecycle ─────────────────────────────────────────────────────── */

/**
 * Load a GGUF model from file. Returns null on failure.
 */
llama_model *llama_model_load_from_file(const char *path_bytes,
                                         llama_model_params params);

/**
 * Free a loaded model.
 */
void llama_free_model(llama_model *model);

/**
 * Return the vocabulary size of the loaded model.
 */
int32_t llama_n_vocab(const llama_model *model);

/**
 * Return the beginning-of-sequence token ID, or -1 if not available.
 */
llama_token llama_token_bos(const llama_model *model);

/**
 * Return the end-of-sequence token ID, or -1 if not available.
 */
llama_token llama_token_eos(const llama_model *model);

/**
 * Return the newline token ID, or -1 if not available.
 */
llama_token llama_token_nl(const llama_model *model);

/**
 * Return the padding token ID. Returns -1 (no dedicated padding token).
 */
llama_token llama_token_pad(const llama_model *model);

/**
 * Return the training context length for a model.
 * For standard GGUF models this equals the model's default context window.
 */
int32_t llama_model_n_ctx_train(const llama_model *model);

/* ── Context lifecycle ───────────────────────────────────────────────────── */

/**
 * Create a new inference context for a loaded model.
 */
llama_context *llama_new_context_with_model(llama_model *model,
                                              llama_context_params params);

/**
 * Free a context.
 */
void llama_free(llama_context *ctx);

/**
 * Return the context's maximum sequence length.
 */
int32_t llama_n_ctx(const llama_context *ctx);

/* ── Forward pass ────────────────────────────────────────────────────────── */

/**
 * Run a forward pass over `n_tokens` tokens, extending the KV cache.
 *
 * Tokens accumulate across calls. Synthetic logits are written to the context
 * logit buffer (accessible via `llama_get_logits`): -20.0 for all tokens,
 * +20.0 at the predicted next token position. Compatible with all sampling
 * functions.
 *
 * Returns 0 on success, -1 on error or invalid arguments.
 */
int32_t llama_eval(llama_context *ctx,
                   const int32_t *tokens,
                   int32_t n_tokens,
                   int32_t n_past);

/**
 * Return a pointer to the logit buffer (one float per vocabulary token).
 *
 * Valid until the next `llama_eval` call or until the context is freed.
 * Returns null if `ctx` is null.
 */
const float *llama_get_logits(const llama_context *ctx);

/* ── Tokenization ────────────────────────────────────────────────────────── */

/**
 * Tokenize a text string into token IDs.
 *
 * Returns the number of tokens written. Returns -(n_needed) if the output
 * buffer is too small (callers should retry with a larger buffer).
 * Returns -1 on other errors (null arguments, invalid UTF-8).
 */
int32_t llama_tokenize(const llama_model *model,
                       const char *text,
                       int32_t text_len,
                       llama_token *tokens,
                       int32_t n_tokens_max,
                       bool add_bos,
                       bool special);

/**
 * Decode a single token ID to its UTF-8 string piece.
 *
 * Returns the number of bytes written (may be 0 for special tokens).
 * Returns -(n_needed) if the buffer is too small.
 * Returns -1 on error.
 */
int32_t llama_token_to_piece(const llama_model *model,
                              llama_token token,
                              char *buf,
                              int32_t length);

/* ── Sampling ────────────────────────────────────────────────────────────── */

/**
 * Apply temperature scaling to logits in-place.
 * `temp = 0` → greedy (collapses to argmax).
 */
void llama_sample_temperature(llama_context *ctx,
                               llama_token_data_array *candidates,
                               float temp);

/**
 * Sample the token with the highest logit (greedy decoding).
 */
llama_token llama_sample_token_greedy(llama_context *ctx,
                                       llama_token_data_array *candidates);

/**
 * Apply top-k filtering (keep only the k highest logits).
 */
void llama_sample_top_k(llama_context *ctx,
                         llama_token_data_array *candidates,
                         int32_t k,
                         size_t min_keep);

/**
 * Apply top-p (nucleus) filtering.
 */
void llama_sample_top_p(llama_context *ctx,
                         llama_token_data_array *candidates,
                         float p,
                         size_t min_keep);

/**
 * Apply repetition penalty to discourage repeated tokens.
 */
void llama_sample_repetition_penalties(llama_context *ctx,
                                        llama_token_data_array *candidates,
                                        const llama_token *last_tokens,
                                        size_t penalty_last_n,
                                        float penalty_repeat,
                                        float penalty_freq,
                                        float penalty_present);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* LLAMA_H */
