//! Direct libllama C API backend (Phase 2).
//!
//! Wraps the real `llama.cpp` library in-process — no subprocess overhead,
//! real `llama_perf_context` throughput stats, and a context pool for true
//! per-request concurrency.
//!
//! # Requirements
//!
//! - `brew install llama.cpp` (installs `libllama.dylib` + `llama.h`)
//! - Enable the feature: `cargo build --features ax-serving-engine/libllama`
//! - Or set `AXS_LLAMA_INCLUDE_DIR` / `AXS_LLAMA_LIB_DIR` for custom paths.
//!
//! # Environment variables
//!
//! | Variable | Default | Description |
//! |---|---|---|
//! | `AXS_LIBLLAMA_N_GPU_LAYERS` | `99` (all) | GPU offload layers |
//! | `AXS_LIBLLAMA_THREADS` | `0` (auto) | CPU threads per context |
//! | `AXS_LIBLLAMA_FLASH_ATTN` | `true` | Enable flash attention |
//! | `AXS_LIBLLAMA_KV_TYPE` | `f16` | KV cache type: `f16`, `q8_0`, `q4_0` |
//! | `AXS_LIBLLAMA_N_BATCH` | `512` | Prompt batch size |
//! | `AXS_LIBLLAMA_POOL_SIZE` | `4` | Max concurrent requests per model |
//!
//! # Architecture
//!
//! Each loaded model gets a `LlamaContextPool` of `pool_size` contexts.
//! `generate()` acquires one context (blocking if all are busy), runs the
//! decode loop on a plain `std::thread`, and releases the context on completion.
//! The model pointer and context pointers are wrapped in safe newtypes that
//! implement `Send`; the model is safe to share (`Sync`) because it is
//! read-only after loading.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unsafe_op_in_unsafe_fn
)]

use std::collections::HashMap;
use std::ffi::CString;
use std::os::raw::c_char;
use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, RwLock};
use std::time::Instant;

use anyhow::{Context, Result};
use tracing::{info, warn};

use crate::{
    ChatMessage, EmbedConfig, EmbedInput, EmbedResult, GenerateEvent, GenerateInput,
    GenerationParams, GenerationStats, InferenceBackend, LoadConfig, ModelHandle, ModelMetadata,
    ThermalMonitor, ThermalState,
};

// ── FFI bindings (generated by build.rs via bindgen) ─────────────────────────

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all,
    unused_imports
)]
pub(crate) mod ffi {
    include!(concat!(env!("OUT_DIR"), "/libllama_bindings.rs"));
}

// ── Handle counter ────────────────────────────────────────────────────────────

static NEXT_LIBLLAMA_HANDLE: AtomicU64 = AtomicU64::new(4_000_000);

fn next_libllama_handle() -> ModelHandle {
    ModelHandle(NEXT_LIBLLAMA_HANDLE.fetch_add(1, Ordering::Relaxed))
}

// ── Safe pointer wrappers ─────────────────────────────────────────────────────

/// Wrapper for `*mut llama_model`. Read-only after load → Send + Sync.
struct LlamaModelPtr(*mut ffi::llama_model);

// SAFETY: llama_model is read-only after `llama_load_model_from_file` returns.
// The llama.cpp documentation explicitly allows concurrent inference from
// multiple contexts sharing the same model pointer.
unsafe impl Send for LlamaModelPtr {}
unsafe impl Sync for LlamaModelPtr {}

/// Wrapper for `*mut llama_context`. Must NOT be shared across threads (not
/// Sync), but can be moved (Send) — enforced by the pool's Mutex.
struct LlamaContextPtr(*mut ffi::llama_context);

// SAFETY: each context is held by exactly one thread at a time, enforced by
// `LlamaContextPool::acquire()` / `LlamaContextPool::release()`.
unsafe impl Send for LlamaContextPtr {}

impl Drop for LlamaContextPtr {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { ffi::llama_free(self.0) };
            self.0 = std::ptr::null_mut();
        }
    }
}

// ── Context pool ──────────────────────────────────────────────────────────────

/// A pool of `llama_context` pointers — at most one per concurrent request.
///
/// `acquire()` blocks until a context is available; `release()` returns it.
/// All contexts are drained (and freed) before the owning model is freed.
struct LlamaContextPool {
    available: Mutex<Vec<LlamaContextPtr>>,
    cv: std::sync::Condvar,
    total: usize,
}

impl LlamaContextPool {
    fn new(contexts: Vec<LlamaContextPtr>) -> Self {
        let total = contexts.len();
        Self {
            available: Mutex::new(contexts),
            cv: std::sync::Condvar::new(),
            total,
        }
    }

    /// Borrow a context, blocking until one is available.
    fn acquire(&self) -> LlamaContextPtr {
        let mut guard = self.available.lock().unwrap();
        loop {
            if let Some(ctx) = guard.pop() {
                return ctx;
            }
            guard = self.cv.wait(guard).unwrap();
        }
    }

    /// Return a context to the pool.
    fn release(&self, ctx: LlamaContextPtr) {
        self.available.lock().unwrap().push(ctx);
        self.cv.notify_one();
    }

    /// Wait for all in-flight requests to return their contexts, then drain
    /// and free every context. Called from `LlamaModelHolder::drop`.
    fn drain_all(&self) {
        let mut guard = self.available.lock().unwrap();
        while guard.len() < self.total {
            guard = self.cv.wait(guard).unwrap();
        }
        guard.clear(); // Drops all LlamaContextPtr — calls llama_free on each.
    }
}

// ── Per-model entry ───────────────────────────────────────────────────────────

/// Holds one loaded model and its associated context pool.
///
/// Field drop order (Rust drops in declaration order): `pool` first (all
/// contexts freed via `LlamaContextPtr::drop`), then `model` freed.
/// The custom `Drop` impl ensures the model pointer is freed after the pool.
struct LlamaModelHolder {
    pool: LlamaContextPool,
    model: LlamaModelPtr,
    meta: ModelMetadata,
}

// SAFETY: LlamaModelPtr is Send+Sync; pool is guarded by Mutex.
unsafe impl Send for LlamaModelHolder {}
unsafe impl Sync for LlamaModelHolder {}

impl Drop for LlamaModelHolder {
    fn drop(&mut self) {
        // 1. Wait for all in-flight requests, then free every context.
        //    This ensures no context outlives the model it references.
        self.pool.drain_all();

        // 2. Free the model pointer.
        if !self.model.0.is_null() {
            info!("libllama: freeing model (arch={})", self.meta.architecture);
            unsafe { ffi::llama_free_model(self.model.0) };
            self.model.0 = std::ptr::null_mut();
        }
    }
}

// ── LibLlamaBackend ───────────────────────────────────────────────────────────

/// `InferenceBackend` implementation using the direct libllama C API.
pub struct LibLlamaBackend {
    models: RwLock<HashMap<ModelHandle, Arc<LlamaModelHolder>>>,
    thermal: ThermalMonitor,
    n_threads: i32,
    flash_attn: bool,
    n_batch: u32,
    pool_size: usize,
}

impl LibLlamaBackend {
    pub fn new() -> Self {
        // Initialize the llama.cpp metal/cpu backend (idempotent).
        unsafe { ffi::llama_backend_init() };

        let n_threads = std::env::var("AXS_LIBLLAMA_THREADS")
            .ok()
            .and_then(|v| v.parse::<i32>().ok())
            .unwrap_or(0); // 0 = llama.cpp auto-detects

        let flash_attn = std::env::var("AXS_LIBLLAMA_FLASH_ATTN")
            .map(|v| v != "0" && v.to_lowercase() != "false")
            .unwrap_or(true);

        let n_batch = std::env::var("AXS_LIBLLAMA_N_BATCH")
            .ok()
            .and_then(|v| v.parse::<u32>().ok())
            .unwrap_or(512);

        let pool_size = std::env::var("AXS_LIBLLAMA_POOL_SIZE")
            .ok()
            .and_then(|v| v.parse::<usize>().ok())
            .unwrap_or(4)
            .max(1);

        info!(
            "libllama: init threads={n_threads} flash_attn={flash_attn} n_batch={n_batch} pool_size={pool_size}"
        );

        Self {
            models: RwLock::new(HashMap::new()),
            thermal: ThermalMonitor::new(),
            n_threads,
            flash_attn,
            n_batch,
            pool_size,
        }
    }
}

impl Default for LibLlamaBackend {
    fn default() -> Self {
        Self::new()
    }
}

impl InferenceBackend for LibLlamaBackend {
    // ── Model lifecycle ───────────────────────────────────────────────────────

    fn load_model(&self, path: &Path, config: LoadConfig) -> Result<(ModelHandle, ModelMetadata)> {
        anyhow::ensure!(path.exists(), "model file not found: {}", path.display());

        let path_str = path
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("non-UTF-8 model path"))?;
        let path_cstr = CString::new(path_str).context("model path contains NUL byte")?;

        let start = Instant::now();

        // ── Load model ────────────────────────────────────────────────────────
        let model_ptr = unsafe {
            let mut params = ffi::llama_model_default_params();

            params.n_gpu_layers = match config.backend_type {
                crate::BackendType::Cpu => 0,
                _ => config.llama_cpp_n_gpu_layers.unwrap_or_else(|| {
                    std::env::var("AXS_LIBLLAMA_N_GPU_LAYERS")
                        .ok()
                        .and_then(|v| v.parse::<i32>().ok())
                        .unwrap_or(99)
                }),
            };

            ffi::llama_load_model_from_file(path_cstr.as_ptr(), params)
        };

        if model_ptr.is_null() {
            anyhow::bail!(
                "llama_load_model_from_file returned NULL for {}",
                path.display()
            );
        }

        info!(
            "libllama: model loaded in {}ms: {}",
            start.elapsed().as_millis(),
            path.display()
        );

        // ── Read metadata from the model ──────────────────────────────────────
        let ctx_len = if config.context_length > 0 {
            config.context_length
        } else {
            unsafe { ffi::llama_model_n_ctx_train(model_ptr) as u32 }
        };

        let (n_layers, n_heads, n_kv_heads, n_embd) = unsafe {
            (
                ffi::llama_model_n_layer(model_ptr) as u32,
                ffi::llama_model_n_head(model_ptr) as u32,
                ffi::llama_model_n_head_kv(model_ptr) as u32,
                ffi::llama_model_n_embd(model_ptr) as u32,
            )
        };

        let vocab = unsafe { ffi::llama_model_get_vocab(model_ptr) };
        let n_vocab = unsafe { ffi::llama_vocab_n_tokens(vocab) as u32 };

        // Architecture name from GGUF header (fast path — no inference needed).
        let arch = crate::gguf_meta::read_gguf_meta(path)
            .map(|m| m.architecture)
            .unwrap_or_else(|_| "gguf-libllama".to_string());

        let peak_rss = crate::current_rss_bytes();
        let load_ms = start.elapsed().as_millis() as u64;

        let meta = ModelMetadata {
            architecture: arch,
            n_layers,
            n_heads,
            n_kv_heads,
            embedding_dim: n_embd,
            vocab_size: n_vocab,
            context_length: ctx_len,
            load_time_ms: load_ms,
            peak_rss_bytes: peak_rss,
        };

        // ── Create context pool ───────────────────────────────────────────────
        let mut contexts = Vec::with_capacity(self.pool_size);
        for i in 0..self.pool_size {
            let ctx_ptr = unsafe {
                let mut params = ffi::llama_context_default_params();
                params.n_ctx = ctx_len;
                params.n_batch = self.n_batch;
                params.n_threads = self.n_threads;
                params.n_threads_batch = self.n_threads;
                params.flash_attn_type = if self.flash_attn {
                    ffi::llama_flash_attn_type_LLAMA_FLASH_ATTN_TYPE_ENABLED
                } else {
                    ffi::llama_flash_attn_type_LLAMA_FLASH_ATTN_TYPE_DISABLED
                };
                ffi::llama_new_context_with_model(model_ptr, params)
            };

            if ctx_ptr.is_null() {
                warn!("libllama: failed to create context {i}/{}", self.pool_size);
                break;
            }
            contexts.push(LlamaContextPtr(ctx_ptr));
        }

        if contexts.is_empty() {
            unsafe { ffi::llama_free_model(model_ptr) };
            anyhow::bail!(
                "libllama: failed to create any contexts for {}",
                path.display()
            );
        }

        info!(
            "libllama: {} context(s) created (pool_size={})",
            contexts.len(),
            self.pool_size
        );

        let holder = Arc::new(LlamaModelHolder {
            pool: LlamaContextPool::new(contexts),
            model: LlamaModelPtr(model_ptr),
            meta: meta.clone(),
        });

        let handle = next_libllama_handle();
        self.models.write().unwrap().insert(handle, holder);

        Ok((handle, meta))
    }

    fn unload_model(&self, handle: ModelHandle) -> Result<()> {
        let entry = self.models.write().unwrap().remove(&handle);
        anyhow::ensure!(
            entry.is_some(),
            "no libllama model loaded with handle {:?}",
            handle
        );
        // Arc<LlamaModelHolder> drops here: pool drains first, then model freed.
        info!("libllama: unloaded model {:?}", handle);
        Ok(())
    }

    // ── Generation ────────────────────────────────────────────────────────────

    fn generate(
        &self,
        handle: ModelHandle,
        input: GenerateInput,
        params: GenerationParams,
        tx: tokio::sync::mpsc::Sender<GenerateEvent>,
    ) -> Result<()> {
        let holder = {
            let guard = self.models.read().unwrap();
            guard
                .get(&handle)
                .cloned()
                .ok_or_else(|| anyhow::anyhow!("invalid libllama model handle {:?}", handle))?
        };

        // Spawn a blocking thread: the llama.cpp C API is synchronous.
        std::thread::spawn(move || {
            // Acquire a context (blocks until one is available in the pool).
            let ctx = holder.pool.acquire();

            let result = run_generate(holder.model.0, ctx.0, &holder.meta, &input, &params, &tx);

            holder.pool.release(ctx);

            if let Err(e) = result {
                warn!("libllama generate error: {e}");
                let _ = tx.blocking_send(GenerateEvent::Error(e.to_string()));
            }
        });

        Ok(())
    }

    // ── Tokenization ──────────────────────────────────────────────────────────

    fn tokenize(&self, handle: ModelHandle, text: &str, add_bos: bool) -> Result<Vec<u32>> {
        let guard = self.models.read().unwrap();
        let holder = guard
            .get(&handle)
            .ok_or_else(|| anyhow::anyhow!("invalid libllama model handle {:?}", handle))?;

        let vocab = unsafe { ffi::llama_model_get_vocab(holder.model.0) };
        let tokens = unsafe { tokenize_text(vocab, text, add_bos) }?;
        Ok(tokens.into_iter().map(|t| t as u32).collect())
    }

    fn decode_tokens(&self, handle: ModelHandle, tokens: &[u32]) -> Result<String> {
        let guard = self.models.read().unwrap();
        let holder = guard
            .get(&handle)
            .ok_or_else(|| anyhow::anyhow!("invalid libllama model handle {:?}", handle))?;

        let vocab = unsafe { ffi::llama_model_get_vocab(holder.model.0) };
        let mut out = String::new();
        for &tok in tokens {
            let piece = unsafe { token_to_piece(vocab, tok as i32) };
            out.push_str(&piece);
        }
        Ok(out)
    }

    fn eos_tokens(&self, handle: ModelHandle) -> Result<Vec<u32>> {
        let guard = self.models.read().unwrap();
        let holder = guard
            .get(&handle)
            .ok_or_else(|| anyhow::anyhow!("invalid libllama model handle {:?}", handle))?;

        let vocab = unsafe { ffi::llama_model_get_vocab(holder.model.0) };
        let eos = unsafe { ffi::llama_vocab_eos(vocab) };
        Ok(vec![eos as u32])
    }

    // ── Thermal ───────────────────────────────────────────────────────────────

    fn thermal_state(&self) -> ThermalState {
        self.thermal.current()
    }

    fn recommended_concurrency(&self) -> usize {
        self.thermal.recommended_concurrency()
    }

    // ── Embeddings ────────────────────────────────────────────────────────────

    fn embed(
        &self,
        handle: ModelHandle,
        inputs: &EmbedInput<'_>,
        config: &EmbedConfig,
    ) -> Result<EmbedResult> {
        let holder = {
            let guard = self.models.read().unwrap();
            guard
                .get(&handle)
                .cloned()
                .ok_or_else(|| anyhow::anyhow!("invalid libllama model handle {:?}", handle))?
        };

        let n_embd = holder.meta.embedding_dim as usize;
        if n_embd == 0 {
            anyhow::bail!("model has no embedding dimension — load with embeddings enabled");
        }

        // Maximum context tokens for truncation.
        let n_ctx = holder.meta.context_length as usize;

        // Acquire a context from the pool.
        let ctx = holder.pool.acquire();

        let result = (|| -> Result<EmbedResult> {
            let vocab = unsafe { ffi::llama_model_get_vocab(holder.model.0) };
            let mut embeddings = Vec::new();
            let mut total_tokens: u32 = 0;

            // Resolve each input to a token sequence.
            let sequences: Vec<Vec<i32>> = match inputs {
                EmbedInput::Strings(texts) => texts
                    .iter()
                    .map(|t| unsafe { tokenize_text(vocab, t, true) })
                    .collect::<Result<_>>()?,
                EmbedInput::Tokens(seqs) => seqs
                    .iter()
                    .map(|s| s.iter().map(|&t| t as i32).collect())
                    .collect(),
            };

            for mut tokens in sequences {
                unsafe { ffi::llama_memory_clear(ffi::llama_get_memory(ctx.0), true) };

                if tokens.is_empty() {
                    embeddings.push(vec![0.0f32; n_embd]);
                    continue;
                }

                // Truncate to context window if requested.
                if config.truncate && tokens.len() > n_ctx {
                    tokens.truncate(n_ctx);
                }

                total_tokens += tokens.len() as u32;
                let n = tokens.len() as i32;

                unsafe {
                    let mut batch = ffi::llama_batch_init(n, 0, 1);
                    batch.n_tokens = n;
                    for (i, &tok) in tokens.iter().enumerate() {
                        *batch.token.add(i) = tok;
                        *batch.pos.add(i) = i as i32;
                        *batch.n_seq_id.add(i) = 1;
                        *(*batch.seq_id.add(i)).add(0) = 0;
                        // logits=true required for pooled embeddings.
                        *batch.logits.add(i) = 1;
                    }

                    let ret = ffi::llama_decode(ctx.0, batch);
                    ffi::llama_batch_free(batch);
                    if ret != 0 {
                        anyhow::bail!("llama_decode failed during embed (ret={ret})");
                    }

                    // Read pooled embedding from the last token position.
                    let embd_ptr = ffi::llama_get_embeddings_ith(ctx.0, n - 1);
                    if embd_ptr.is_null() {
                        anyhow::bail!(
                            "llama_get_embeddings_ith returned NULL — context may not have embeddings enabled"
                        );
                    }
                    let mut embd = std::slice::from_raw_parts(embd_ptr, n_embd).to_vec();

                    // L2-normalise if requested.
                    if config.normalize {
                        let norm: f32 = embd.iter().map(|x| x * x).sum::<f32>().sqrt();
                        if norm > 1e-12 {
                            for x in embd.iter_mut() {
                                *x /= norm;
                            }
                        }
                    }

                    embeddings.push(embd);
                }
            }

            Ok(EmbedResult {
                embeddings,
                prompt_tokens: total_tokens,
            })
        })();

        holder.pool.release(ctx);
        result
    }
}

// ── Unsafe inference helpers ──────────────────────────────────────────────────

/// Compute log probability of `sampled_tok` and top-N alternatives from the
/// current context logits (position -1 = last decoded position).
///
/// Returns `(logprob_of_sampled, [(token_text, logprob); top_n])`.
///
/// # Safety
/// `ctx` must be valid. `llama_get_logits_ith(ctx, -1)` must be valid (called
/// immediately after a decode step).
unsafe fn compute_logprob(
    ctx: *mut ffi::llama_context,
    vocab: *const ffi::llama_vocab,
    sampled_tok: i32,
    n_vocab: usize,
    top_n: usize,
) -> (f32, Vec<(String, f32)>) {
    let logits_ptr = ffi::llama_get_logits_ith(ctx, -1);
    if logits_ptr.is_null() || n_vocab == 0 {
        return (-f32::INFINITY, Vec::new());
    }
    // Guard against special/negative token IDs (e.g. EOS already filtered, but
    // be defensive) and any out-of-range value from the sampler.
    if sampled_tok < 0 || sampled_tok as usize >= n_vocab {
        return (-f32::INFINITY, Vec::new());
    }
    let logits = std::slice::from_raw_parts(logits_ptr, n_vocab);

    // Numerically-stable log-softmax: subtract max before exp.
    let max_logit = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let exp_sum: f64 = logits.iter().map(|&l| ((l - max_logit) as f64).exp()).sum();
    let log_sum = exp_sum.ln() as f32;

    // Log probability of the sampled token.
    let sampled_lp = (logits[sampled_tok as usize] - max_logit) - log_sum;

    // Top-N alternatives (sorted by logit descending).
    let top_entries = if top_n > 0 {
        let mut indexed: Vec<(usize, f32)> = logits.iter().copied().enumerate().collect();
        indexed.sort_unstable_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
        indexed
            .iter()
            .take(top_n)
            .map(|(i, logit)| {
                let lp = (logit - max_logit) - log_sum;
                let piece = token_to_piece(vocab, *i as i32);
                (piece, lp)
            })
            .collect()
    } else {
        Vec::new()
    };

    (sampled_lp, top_entries)
}

/// Convert a single token to its UTF-8 text piece.
///
/// # Safety
/// `vocab` must be a valid, non-null vocab pointer returned by
/// `llama_model_get_vocab`. The pointer remains valid for the lifetime of the
/// owning `LlamaModelHolder`.
unsafe fn token_to_piece(vocab: *const ffi::llama_vocab, token: i32) -> String {
    let mut buf = vec![0u8; 32];
    let n = ffi::llama_token_to_piece(
        vocab,
        token,
        buf.as_mut_ptr() as *mut c_char,
        buf.len() as i32,
        0,     // lstrip: 0 = no stripping
        false, // special: do not render special tokens
    );
    if n < 0 {
        let needed = (-n) as usize;
        buf.resize(needed, 0);
        let n2 = ffi::llama_token_to_piece(
            vocab,
            token,
            buf.as_mut_ptr() as *mut c_char,
            buf.len() as i32,
            0,
            false,
        );
        if n2 > 0 {
            String::from_utf8_lossy(&buf[..n2 as usize]).into_owned()
        } else {
            String::new()
        }
    } else if n > 0 {
        String::from_utf8_lossy(&buf[..n as usize]).into_owned()
    } else {
        String::new()
    }
}

/// Tokenize `text` into a `Vec<llama_token>` (i32).
///
/// # Safety
/// `vocab` must be valid and non-null.
unsafe fn tokenize_text(
    vocab: *const ffi::llama_vocab,
    text: &str,
    add_bos: bool,
) -> Result<Vec<i32>> {
    let ctext = CString::new(text).context("text contains NUL byte")?;
    let max_tokens = (text.len() as i32 + 2).max(16);
    let mut tokens = vec![0i32; max_tokens as usize];

    let n = ffi::llama_tokenize(
        vocab,
        ctext.as_ptr(),
        text.len() as i32,
        tokens.as_mut_ptr(),
        max_tokens,
        add_bos,
        false, // special
    );

    if n < 0 {
        // Buffer too small — retry with the exact size reported.
        let needed = (-n) as usize;
        tokens.resize(needed, 0);
        let n2 = ffi::llama_tokenize(
            vocab,
            ctext.as_ptr(),
            text.len() as i32,
            tokens.as_mut_ptr(),
            needed as i32,
            add_bos,
            false,
        );
        anyhow::ensure!(n2 >= 0, "llama_tokenize failed (n={})", n2);
        tokens.truncate(n2 as usize);
    } else {
        tokens.truncate(n as usize);
    }

    Ok(tokens)
}

/// Build a llama_sampler chain from `GenerationParams`.
///
/// Chain layout (standard path):
///   penalties → top_k → top_p → temperature → dist
///
/// Greedy path (temperature = 0 or None):
///   greedy
///
/// Mirostat path:
///   mirostat_v2 → dist
///
/// # Safety
/// `model` must be valid and non-null (needed for grammar sampler if used).
unsafe fn build_sampler(
    _model: *const ffi::llama_model,
    params: &GenerationParams,
) -> *mut ffi::llama_sampler {
    let chain_params = ffi::llama_sampler_chain_default_params();
    let chain = ffi::llama_sampler_chain_init(chain_params);

    let seed = params.seed.unwrap_or_else(|| {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .subsec_nanos() as u64
    }) as u32;

    let temp = params.temperature.unwrap_or(0.0);

    // Greedy decoding.
    if temp <= 0.0 {
        ffi::llama_sampler_chain_add(chain, ffi::llama_sampler_init_greedy());
        return chain;
    }

    // Mirostat overrides top-k/top-p.
    if params.mirostat.unwrap_or(0) > 0 {
        let tau = params.mirostat_tau.unwrap_or(5.0) as f32;
        let eta = params.mirostat_eta.unwrap_or(0.1) as f32;
        // mirostat_v2 is the stable public API (v1 requires common.h internals).
        ffi::llama_sampler_chain_add(chain, ffi::llama_sampler_init_mirostat_v2(seed, tau, eta));
        ffi::llama_sampler_chain_add(chain, ffi::llama_sampler_init_dist(seed));
        return chain;
    }

    // Repetition penalties.
    let rep = params.repeat_penalty.unwrap_or(1.0) as f32;
    let freq = params.frequency_penalty.unwrap_or(0.0) as f32;
    let pres = params.presence_penalty.unwrap_or(0.0) as f32;
    if rep != 1.0 || freq != 0.0 || pres != 0.0 {
        ffi::llama_sampler_chain_add(
            chain,
            ffi::llama_sampler_init_penalties(64, rep, freq, pres),
        );
    }

    // Top-k.
    if let Some(k) = params.top_k
        && k > 0
    {
        ffi::llama_sampler_chain_add(chain, ffi::llama_sampler_init_top_k(k as i32));
    }

    // Top-p.
    if let Some(p) = params.top_p
        && p < 1.0
    {
        ffi::llama_sampler_chain_add(chain, ffi::llama_sampler_init_top_p(p as f32, 1));
    }

    // Temperature + distribution sampler.
    ffi::llama_sampler_chain_add(chain, ffi::llama_sampler_init_temp(temp as f32));
    ffi::llama_sampler_chain_add(chain, ffi::llama_sampler_init_dist(seed));

    chain
}

/// Apply a simple chat template by concatenating `<role>: <content>\n` pairs.
///
/// llama.cpp's `llama_chat_apply_template` is not yet in the bindgen
/// allowlist; this covers basic use cases. Production callers can override
/// by building prompts before calling `generate()`.
fn apply_simple_chat_template(msgs: &[ChatMessage]) -> String {
    msgs.iter()
        .map(|m| {
            let text = match &m.content {
                serde_json::Value::String(s) => s.clone(),
                serde_json::Value::Array(parts) => parts
                    .iter()
                    .filter_map(|p| {
                        if p["type"].as_str() == Some("text") {
                            p["text"].as_str().map(|s| s.to_string())
                        } else {
                            None
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(""),
                other => other.to_string(),
            };
            format!("{}: {}\n", m.role, text)
        })
        .collect()
}

/// Prefill + decode loop for one generation request.
///
/// Runs entirely on the calling (non-tokio) thread. Communicates via
/// `tx.blocking_send()`.
fn run_generate(
    model: *mut ffi::llama_model,
    ctx: *mut ffi::llama_context,
    meta: &ModelMetadata,
    input: &GenerateInput,
    params: &GenerationParams,
    tx: &tokio::sync::mpsc::Sender<GenerateEvent>,
) -> Result<()> {
    // 1. Clear KV cache from any previous request on this context.
    unsafe { ffi::llama_memory_clear(ffi::llama_get_memory(ctx), true) };

    // 2. Tokenize input.
    let vocab = unsafe { ffi::llama_model_get_vocab(model) };
    let tokens: Vec<i32> = match input {
        GenerateInput::Tokens(toks) => toks.iter().map(|&t| t as i32).collect(),
        GenerateInput::Text(text) => unsafe { tokenize_text(vocab, text, true) }?,
        GenerateInput::Chat(msgs) => {
            let prompt = apply_simple_chat_template(msgs);
            unsafe { tokenize_text(vocab, &prompt, true) }?
        }
    };

    anyhow::ensure!(
        !tokens.is_empty(),
        "empty token sequence after tokenization"
    );

    let ctx_size = meta.context_length as usize;
    let n_input = tokens.len();
    anyhow::ensure!(
        n_input < ctx_size,
        "input ({n_input} tokens) exceeds context length ({ctx_size})"
    );

    let max_new = params.max_tokens.unwrap_or(512).min(ctx_size - n_input);

    let eos = unsafe { ffi::llama_vocab_eos(vocab) };

    // 3. Build sampler chain.
    let sampler = unsafe { build_sampler(model, params) };

    // 4. Prefill — all input tokens in one batch, logits only on the last.
    let prefill_start = Instant::now();
    let prefill_ok = unsafe {
        let mut batch = ffi::llama_batch_init(n_input as i32, 0, 1);
        batch.n_tokens = n_input as i32;
        for (i, &tok) in tokens.iter().enumerate() {
            *batch.token.add(i) = tok;
            *batch.pos.add(i) = i as i32;
            *batch.n_seq_id.add(i) = 1;
            *(*batch.seq_id.add(i)).add(0) = 0;
            // Only compute logits for the last position in the prefill batch.
            *batch.logits.add(i) = if i == n_input - 1 { 1 } else { 0 };
        }
        let ret = ffi::llama_decode(ctx, batch);
        ffi::llama_batch_free(batch);
        ret == 0
    };

    if !prefill_ok {
        if !sampler.is_null() {
            unsafe { ffi::llama_sampler_free(sampler) };
        }
        anyhow::bail!("llama_decode (prefill) failed");
    }
    let prefill_ms = prefill_start.elapsed().as_secs_f64() * 1000.0;

    let emit_logprobs = params.logprobs.unwrap_or(false);
    let n_top_logprobs = params.top_logprobs.unwrap_or(0) as usize;
    let n_vocab = unsafe { ffi::llama_vocab_n_tokens(vocab) as usize };

    // 5. Sample the first token from the prefill logits.
    //    idx = -1 means "last position with computed logits".
    let mut next_tok = unsafe { ffi::llama_sampler_sample(sampler, ctx, -1) };
    unsafe { ffi::llama_sampler_accept(sampler, next_tok) };

    // 6. Decode loop.
    let decode_start = Instant::now();
    let mut n_decoded = 0usize;
    let mut current_pos = n_input;
    let mut accumulated = String::new();

    loop {
        // Check EOS.
        if next_tok == eos {
            break;
        }

        // Convert token → text, emit.
        let piece = unsafe { token_to_piece(vocab, next_tok) };
        accumulated.push_str(&piece);

        // Emit token event (and optionally logprob).
        if emit_logprobs {
            let (lp, top) =
                unsafe { compute_logprob(ctx, vocab, next_tok, n_vocab, n_top_logprobs) };
            if tx
                .blocking_send(GenerateEvent::Token(piece.clone()))
                .is_err()
            {
                break;
            }
            if tx
                .blocking_send(GenerateEvent::TokenLogprob { logprob: lp, top })
                .is_err()
            {
                break;
            }
        } else if tx.blocking_send(GenerateEvent::Token(piece)).is_err() {
            // Receiver dropped (client disconnected).
            break;
        }

        n_decoded += 1;

        // Check stop sequences.
        if params
            .stop_seqs
            .iter()
            .any(|seq| accumulated.ends_with(seq.as_str()))
        {
            break;
        }

        if n_decoded >= max_new {
            break;
        }

        // Decode step: submit the token we just generated, advance position.
        let decode_ok = unsafe {
            let mut batch = ffi::llama_batch_init(1, 0, 1);
            batch.n_tokens = 1;
            *batch.token.add(0) = next_tok;
            *batch.pos.add(0) = current_pos as i32;
            *batch.n_seq_id.add(0) = 1;
            *(*batch.seq_id.add(0)).add(0) = 0;
            *batch.logits.add(0) = 1;

            let ret = ffi::llama_decode(ctx, batch);
            ffi::llama_batch_free(batch);
            current_pos += 1;
            ret == 0
        };

        if !decode_ok {
            let _ = tx.blocking_send(GenerateEvent::Error(
                "llama_decode failed during generation".into(),
            ));
            break;
        }

        // Sample next token.
        next_tok = unsafe { ffi::llama_sampler_sample(sampler, ctx, -1) };
        unsafe { ffi::llama_sampler_accept(sampler, next_tok) };
    }

    let decode_ms = decode_start.elapsed().as_secs_f64() * 1000.0;

    // 7. Free sampler.
    if !sampler.is_null() {
        unsafe { ffi::llama_sampler_free(sampler) };
    }

    // 8. Compute throughput.
    let prefill_tps = if prefill_ms > 0.0 {
        (n_input as f64) / (prefill_ms / 1000.0)
    } else {
        0.0
    };
    let decode_tps = if n_decoded > 0 && decode_ms > 0.0 {
        (n_decoded as f64) / (decode_ms / 1000.0)
    } else {
        0.0
    };

    let _ = tx.blocking_send(GenerateEvent::Done(GenerationStats {
        prompt_tokens: n_input,
        completion_tokens: n_decoded,
        prefill_tok_per_sec: prefill_tps,
        decode_tok_per_sec: decode_tps,
    }));

    Ok(())
}
